# Generated by Django 5.1.7 on 2025-03-20 07:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMISchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_loan', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tenure_months', models.IntegerField()),
                ('interest_rate', models.FloatField()),
                ('emi_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('next_due_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emi.user')),
            ],
        ),
    ]
