# Generated by Django 5.0.1 on 2025-04-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emi', '0004_rename_stripe_payment_intent_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('calculation', 'Calculation'), ('eligibility', 'Eligibility'), ('trigger', 'Trigger'), ('action', 'Action')], max_length=20)),
                ('condition', models.TextField(help_text='Python-executable condition code or logic')),
                ('action', models.TextField(help_text='Python-executable action code or logic')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1)),
                ('scope', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
