# Generated by Django 5.0.1 on 2025-04-14 05:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emi', '0005_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='action',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='condition',
        ),
        migrations.AddField(
            model_name='rule',
            name='function_name',
            field=models.CharField(default=django.utils.timezone.now, help_text='Name of the rule function to execute', max_length=100),
            preserve_default=False,
        ),
    ]
