# Generated by Django 5.0.1 on 2025-04-14 08:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emi', '0006_remove_rule_action_remove_rule_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='function_name',
        ),
        migrations.AddField(
            model_name='rule',
            name='action',
            field=models.TextField(blank=True, help_text='Python-executable action logic'),
        ),
        migrations.AddField(
            model_name='rule',
            name='condition',
            field=models.TextField(default=django.utils.timezone.now, help_text='Python-executable condition logic'),
            preserve_default=False,
        ),
    ]
